// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euffsnwbkutetfotttck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZmZzbndia3V0ZXRmb3R0dGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTE3ODUsImV4cCI6MjA2ODUyNzc4NX0.9Ndz6OW66St4iu2JYjCtJqKxqdRatoXKCPPbMSBPfm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});